import logging
from pathlib import Path

import pytest
from _pytest.logging import LogCaptureFixture

from dash_license_scan import parsers


def test_parse_pypi_supports_pinned_requirements(
    tmp_path: Path, caplog: LogCaptureFixture
):
    req = tmp_path / "requirements.txt"
    req.write_text("""
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile
#
foo==1.2.3 \\
    --hash=sha256:12c49186003b9f69a028615da883ef97035ea2119a9e3f93a00091b3a27088a6 \\
    --hash=sha256:f389e2997de33d038c5065fd85bff351fbdc62fa6d6371c7b947fc3bce8d437d
    # via -r requirements.in
""")

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(req)

    assert deps == ["pypi/pypi/-/foo/1.2.3"]
    assert caplog.text == ""


def test_parse_pypi_warns_on_unknown_lines(tmp_path: Path, caplog: LogCaptureFixture):
    req = tmp_path / "requirements.txt"
    req.write_text("bar @ git+https://github.com/ORG/bar.git@v1.4.0")

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(req)

    assert deps == []
    assert "Skipping unsupported" in caplog.text


def test_parse_crate_accepts_crates_io(tmp_path: Path):
    cargo = tmp_path / "Cargo.lock"
    cargo.write_text(
        """
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.203"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "log"
version = "0.4.22"
source = "registry+https://github.com/rust-lang/crates.io-index"
"""
    )

    deps = parsers.parse(cargo)

    assert deps == [
        "crate/cratesio/-/serde/1.0.203",
        "crate/cratesio/-/log/0.4.22",
    ]


def test_parse_crate_rejects_unknown_registry(tmp_path: Path):
    cargo = tmp_path / "Cargo.lock"
    cargo.write_text(
        """
[[package]]
name = "local"
version = "0.1.0"
source = "registry+https://example.com/index"
"""
    )

    with pytest.raises(ValueError):  # noqa: PT011
        parsers.parse(cargo)


def test_parse_uv_lock_filters_non_pypi(tmp_path: Path, caplog: LogCaptureFixture):
    uv = tmp_path / "uv.lock"
    uv.write_text(
        """
version = 1
revision = 1
requires-python = ">=3.10"

[[package]]
name = "requests"
version = "2.32.3"

[[package]]
name = "custom"
version = "0.0.1"
source = { registry = "https://example.com/simple" }
"""
    )

    deps = parsers.parse(uv)

    assert deps == ["pypi/pypi/-/requests/2.32.3"]


def test_parse_uv_lock_warns_on_invalid_structure(
    tmp_path: Path, caplog: LogCaptureFixture
):
    uv = tmp_path / "uv.lock"
    uv.write_text("""[package]\nname = 'oops'""")

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(uv)

    assert deps == []
    assert "Invalid uv.lock" in caplog.text


def test_parse_cdx_extracts_dependencies_from_sbom():
    """Test that CycloneDX SBOM is parsed correctly."""
    cdx_file = Path(__file__).parent / "resources" / "sbom.cdx.json"

    deps = parsers.parse(cdx_file)

    # Should extract cargo dependencies from purl
    assert "crate/cratesio/-/serde/1.0.228" in deps
    assert "crate/cratesio/-/proc-macro2/1.0.106" in deps
    assert "crate/cratesio/-/unicode-ident/1.0.22" in deps

    # Should have many dependencies from the SBOM
    assert len(deps) > 10


def test_parse_spdx_extracts_dependencies_from_sbom():
    """Test that SPDX SBOM is parsed correctly."""
    spdx_file = Path(__file__).parent / "resources" / "sbom.spdx.json"

    deps = parsers.parse(spdx_file)

    # Should extract cargo dependencies from purl
    assert "crate/cratesio/-/serde/1.0.228" in deps
    assert "crate/cratesio/-/proc-macro2/1.0.106" in deps
    assert "crate/cratesio/-/unicode-ident/1.0.22" in deps

    # Should have many dependencies from the SBOM
    assert len(deps) > 10

    # Should not include the root package
    assert "kyron_example" not in " ".join(deps)


def test_parse_cdx_handles_invalid_json(tmp_path: Path, caplog: LogCaptureFixture):
    """Test that invalid CycloneDX JSON is handled gracefully."""
    cdx = tmp_path / "sbom.cdx.json"
    cdx.write_text("{invalid json")

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(cdx)

    assert deps == []
    assert "Failed to parse" in caplog.text


def test_parse_spdx_handles_invalid_json(tmp_path: Path, caplog: LogCaptureFixture):
    """Test that invalid SPDX JSON is handled gracefully."""
    spdx = tmp_path / "sbom.spdx.json"
    spdx.write_text("{invalid json")

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(spdx)

    assert deps == []
    assert "Failed to parse" in caplog.text


def test_parse_cdx_validates_format(tmp_path: Path, caplog: LogCaptureFixture):
    """Test that non-CycloneDX JSON is handled gracefully (returns empty list)."""
    cdx = tmp_path / "sbom.cdx.json"
    cdx.write_text('{"format": "something else"}')

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(cdx)

    # The CycloneDX library is lenient and doesn't validate format strictly,
    # but will return empty components, so we get an empty list
    assert deps == []


def test_parse_spdx_validates_format(tmp_path: Path, caplog: LogCaptureFixture):
    """Test that non-SPDX JSON is rejected."""
    spdx = tmp_path / "sbom.spdx.json"
    spdx.write_text('{"version": "1.0"}')

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(spdx)

    assert deps == []
    assert "Invalid SPDX" in caplog.text


def test_parse_spdx_normalizes_non_standard_license_expressions(
    tmp_path: Path, caplog: LogCaptureFixture
):
    """Test that non-standard license expressions (using /) are normalized to SPDX standard (OR)."""
    spdx = tmp_path / "sbom.spdx.json"
    spdx.write_text("""
{
  "spdxVersion": "SPDX-2.3",
  "packages": [
    {
      "SPDXID": "SPDXRef-Package1",
      "name": "test-package",
      "licenseConcluded": "MIT/Apache-2.0",
      "licenseDeclared": "MIT/Apache-2.0",
      "externalRefs": [
        {
          "referenceType": "purl",
          "referenceLocator": "pkg:cargo/test-package@1.0.0"
        }
      ]
    }
  ]
}
""")

    with caplog.at_level(logging.DEBUG):
        deps = parsers.parse(spdx)

    assert deps == ["crate/cratesio/-/test-package/1.0.0"]
    # Check that normalization happened
    assert (
        "Normalizing non-standard license expression: 'MIT/Apache-2.0'" in caplog.text
    )
    assert "Normalized to: 'MIT OR Apache-2.0'" in caplog.text
    assert (
        "Found license for crate/cratesio/-/test-package/1.0.0: MIT OR Apache-2.0"
        in caplog.text
    )
