import logging
from pathlib import Path

import pytest
from _pytest.logging import LogCaptureFixture

from dash_license_scan import parsers


def test_parse_pypi_supports_pinned_requirements(tmp_path: Path, caplog: LogCaptureFixture) -> None:
    req = tmp_path / "requirements.txt"
    req.write_text("""
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile
#
foo==1.2.3 \\
    --hash=sha256:12c49186003b9f69a028615da883ef97035ea2119a9e3f93a00091b3a27088a6 \\
    --hash=sha256:f389e2997de33d038c5065fd85bff351fbdc62fa6d6371c7b947fc3bce8d437d
    # via -r requirements.in
""")

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(req)

    assert deps == ["pypi/pypi/-/foo/1.2.3"]
    assert caplog.text == ""


def test_parse_pypi_warns_on_unknown_lines(tmp_path: Path, caplog: LogCaptureFixture) -> None:
    req = tmp_path / "requirements.txt"
    req.write_text("bar @ git+https://github.com/ORG/bar.git@v1.4.0")

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(req)

    assert deps == []
    assert "Skipping unsupported" in caplog.text


def test_parse_crate_accepts_crates_io(tmp_path: Path) -> None:
    cargo = tmp_path / "Cargo.lock"
    cargo.write_text(
        """
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.203"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "log"
version = "0.4.22"
source = "registry+https://github.com/rust-lang/crates.io-index"
"""
    )

    deps = parsers.parse(cargo)

    assert deps == [
        "crate/cratesio/-/serde/1.0.203",
        "crate/cratesio/-/log/0.4.22",
    ]


def test_parse_crate_rejects_unknown_registry(tmp_path: Path) -> None:
    cargo = tmp_path / "Cargo.lock"
    cargo.write_text(
        """
[[package]]
name = "local"
version = "0.1.0"
source = "registry+https://example.com/index"
"""
    )

    with pytest.raises(ValueError):
        parsers.parse(cargo)


def test_parse_uv_lock_filters_non_pypi(tmp_path: Path, caplog: LogCaptureFixture) -> None:
    uv = tmp_path / "uv.lock"
    uv.write_text(
        """
version = 1
revision = 1
requires-python = ">=3.10"

[[package]]
name = "requests"
version = "2.32.3"

[[package]]
name = "custom"
version = "0.0.1"
source = { registry = "https://example.com/simple" }
"""
    )

    deps = parsers.parse(uv)

    assert deps == ["pypi/pypi/-/requests/2.32.3"]


def test_parse_uv_lock_warns_on_invalid_structure(tmp_path: Path, caplog: LogCaptureFixture) -> None:
    uv = tmp_path / "uv.lock"
    uv.write_text("""[package]\nname = 'oops'""")

    with caplog.at_level(logging.WARNING):
        deps = parsers.parse(uv)

    assert deps == []
    assert "Invalid uv.lock" in caplog.text
